"""Configure and open Spyder 5.x in an isolated, verbose way."""

from __future__ import annotations

import argparse
import os
import shutil
import stat
import subprocess
import sys
import tempfile
from collections.abc import Sequence
from pathlib import Path

from rich import box
from rich.console import Console
from rich.panel import Panel
from rich.table import Table
from rich.text import Text

FONT_FAMILY = "JetBrains Mono"
REPO_URL = "https://github.com/bernardogoltz/setup-spyder"
AUTHOR = "@bernardogoltz"

WINDOWS = sys.platform == "win32"

#: Names hidden from Spyder's Project pane, on top of the ones Spyder already
#: hides itself (``.spyproject``, ``__pycache__``, ``.git``, ``.pytest_cache``,
#: ``.ipynb_checkpoints``, ``.hg``, ``.svn``, ``.DS_Store``, ``Thumbs.db``,
#: ``.directory``). Matched by basename, at any depth in the tree.
HIDDEN_PATHS = (
    # Virtual environments
    ".venv",
    "venv",
    ".env",
    "env",
    ".tox",
    # Build and distribution artifacts
    "dist",
    "build",
    ".eggs",
    "node_modules",
    # Tool caches
    ".ruff_cache",
    ".mypy_cache",
    ".coverage",
    "htmlcov",
    # Repository and tooling metadata
    ".claude",
    ".docs",
    ".github",
    ".gitlab",
    ".gitignore",
    ".gitattributes",
    ".editorconfig",
    ".dockerignore",
    ".python-version",
    ".pre-commit-config.yaml",
    "uv.lock",
    "poetry.lock",
    # Windows folder settings, the one bit of OS clutter Spyder does not hide
    "desktop.ini",
)

#: Spyder starts the IDE in-process, so the Project pane filter has to be
#: patched before ``spyder.app.start`` builds the window — hence a launcher
#: script instead of calling the ``spyder`` executable directly. The patch
#: reaches into Spyder internals, so it is best-effort: on a Spyder that moved
#: them, the IDE still opens, just with the clutter visible.
LAUNCHER_TEMPLATE = '''\
"""Generated by setup-spyder — do not edit by hand.

Hides development clutter from Spyder's Project pane, then starts the IDE.
"""

import sys

# `spyder.app.start` parses the command line at import time, so argv comes first.
sys.argv = {argv!r}

HIDDEN = {hidden!r}

try:
    from spyder.plugins.projects.widgets.projectexplorer import ProxyModel

    ProxyModel.PATHS_TO_HIDE = sorted(
        set(getattr(ProxyModel, "PATHS_TO_HIDE", [])) | set(HIDDEN)
    )
    # PATHS_TO_SHOW wins over PATHS_TO_HIDE, so drop whatever we are hiding.
    ProxyModel.PATHS_TO_SHOW = [
        path
        for path in getattr(ProxyModel, "PATHS_TO_SHOW", [])
        if path not in HIDDEN
    ]
except Exception as exc:  # pragma: no cover - depends on the Spyder version
    print(
        "setup-spyder: could not hide files from the Project pane on this "
        f"Spyder version ({{exc}}); opening it anyway.",
        file=sys.stderr,
    )

from spyder.app.start import main

sys.exit(main())
'''


def font_dirs() -> tuple[Path, ...]:
    """Directories the current platform installs fonts into (user first)."""
    if sys.platform == "win32":
        local = os.environ.get("LOCALAPPDATA") or Path.home() / "AppData" / "Local"
        windir = os.environ.get("WINDIR") or r"C:\Windows"
        return (
            Path(local) / "Microsoft" / "Windows" / "Fonts",
            Path(windir) / "Fonts",
        )
    if sys.platform == "darwin":
        return (
            Path.home() / "Library" / "Fonts",
            Path("/Library/Fonts"),
            Path("/System/Library/Fonts"),
        )
    return (
        Path.home() / ".local" / "share" / "fonts",
        Path("/usr/local/share/fonts"),
        Path("/usr/share/fonts"),
    )


def force_writable(path: Path) -> None:
    """Clear the read-only bit Windows leaves on hardlinked cache files."""
    try:
        path.chmod(path.stat().st_mode | stat.S_IWRITE)
    except OSError:  # pragma: no cover - the file is about to be deleted anyway
        pass


def remove_tree(path: Path) -> None:
    """Delete a directory tree, retrying past files Windows marks read-only."""
    shutil.rmtree(path, ignore_errors=True)
    if not path.is_dir():
        return
    for item in path.rglob("*"):
        force_writable(item)
    force_writable(path)
    shutil.rmtree(path, ignore_errors=True)


def enable_utf8_output() -> None:
    """Let the Windows console print the ✓/◆ glyphs instead of crashing on cp1252."""
    for stream in (sys.stdout, sys.stderr):
        reconfigure = getattr(stream, "reconfigure", None)
        if reconfigure is None:
            continue
        encoding = (getattr(stream, "encoding", "") or "").lower()
        if encoding.replace("-", "") == "utf8":
            continue
        try:
            reconfigure(encoding="utf-8", errors="replace")
        except (OSError, ValueError):  # pragma: no cover - depends on the console
            pass


FONT_DIRS = font_dirs()

if WINDOWS:
    enable_utf8_output()

console = Console(highlight=False)


def _prefix() -> Text:
    return Text("setup-spyder", style="bold cyan")


def log(message: str) -> None:
    console.print(Text.assemble(_prefix(), "  ", (message, "white")), soft_wrap=True)


def log_ok(message: str) -> None:
    console.print(
        Text.assemble(_prefix(), "  ", ("✓ ", "bold green"), (message, "green")),
        soft_wrap=True,
    )


def log_warn(message: str) -> None:
    console.print(
        Text.assemble(_prefix(), "  ", ("! ", "bold yellow"), (message, "yellow")),
        soft_wrap=True,
    )


def log_error(message: str) -> None:
    console.print(
        Text.assemble(_prefix(), "  ", ("✗ ", "bold red"), (message, "red")),
        soft_wrap=True,
    )


def log_kv(key: str, value: object) -> None:
    console.print(
        Text.assemble(
            _prefix(),
            "    ",
            (f"{key}: ", "dim cyan"),
            (str(value), "bold white"),
        ),
        soft_wrap=True,
    )


def print_banner(version: str, workdir: Path) -> None:
    body = Text()
    body.append("setup-spyder", style="bold white")
    body.append(f"  v{version}", style="dim")
    body.append("  ·  ", style="dim")
    body.append(f"{AUTHOR}\n", style="bold bright_magenta")
    body.append("isolated Spyder 5.x", style="cyan")
    body.append("  ·  ", style="dim")
    body.append(FONT_FAMILY, style="magenta")
    body.append("  ·  ", style="dim")
    body.append("wrap lines\n\n", style="green")
    body.append("Hello — opening the project ", style="white")
    body.append(workdir.name, style="bold bright_cyan")
    body.append("\n")
    body.append(str(workdir), style="dim")
    console.print()
    console.print(
        Panel(
            body,
            title="[bold cyan]◆ setup-spyder[/]",
            subtitle="[dim]isolated environment · leaves ~/.spyder-py3 untouched[/]",
            border_style="bright_cyan",
            box=box.ROUNDED,
            padding=(1, 2),
        )
    )
    console.print()


def print_env(workdir: Path) -> None:
    table = Table(
        box=box.SIMPLE,
        show_header=False,
        padding=(0, 2),
        expand=False,
    )
    table.add_column(style="dim cyan")
    table.add_column(style="bold white")
    table.add_row("Python", sys.version.split()[0])
    table.add_row("Executable", sys.executable)
    table.add_row("Environment", sys.prefix)
    table.add_row("Workdir", str(workdir))
    console.print(table)


def jetbrains_mono_installed() -> list[Path]:
    hits: list[Path] = []
    for directory in FONT_DIRS:
        if not directory.is_dir():
            continue
        hits.extend(sorted(directory.glob("JetBrainsMono*")))
        hits.extend(sorted(directory.glob("JetBrainsMonoNerdFont*")))
    return hits


def spyder_default_font() -> str:
    """Spyder's default monospace font (Menlo on macOS, Ubuntu Mono, etc.)."""
    try:
        from spyder.config.fonts import MONOSPACE

        return MONOSPACE[0]
    except Exception:
        return "Monospace"


def resolve_editor_font() -> tuple[str, list[Path]]:
    """Try JetBrains Mono; fall back to Spyder's default font when missing."""
    try:
        hits = jetbrains_mono_installed()
        if not hits:
            raise FileNotFoundError(FONT_FAMILY)
        return FONT_FAMILY, hits
    except Exception:
        default = spyder_default_font()
        log_warn(
            f"{FONT_FAMILY} unavailable; using Spyder's default font ({default})"
        )
        return default, []


def ensure_spyproject(root: Path) -> Path:
    """Create `.spyproject` in the opened repository, if it is not there yet."""
    spyproject = root / ".spyproject"
    if spyproject.is_dir():
        log_ok(f".spyproject already exists: {spyproject}")
        return spyproject

    log(f"Creating .spyproject in {root}")
    (spyproject / "config").mkdir(parents=True, exist_ok=True)
    from spyder.plugins.projects.api import EmptyProject

    EmptyProject(root_path=str(root))

    files = sorted(
        path.relative_to(root) for path in spyproject.rglob("*") if path.is_file()
    )
    if files:
        log_ok(f".spyproject ready ({len(files)} file(s)):")
        for relative in files:
            log_kv("file", relative)
    else:
        log_warn(".spyproject created, but no config file showed up")
    return spyproject


def apply_spyder_config(
    conf_dir: Path, font_family: str | None = None
) -> tuple[object, object]:
    os.environ["SPYDER_CONFDIR"] = str(conf_dir)
    from spyder.config.manager import CONF

    if font_family is None:
        font_family, _ = resolve_editor_font()

    log(f"Applying font {font_family!r}")
    CONF.set("appearance", "font/family", [font_family])
    log("Turning on wrap lines in the editor (editor.wrap = True)")
    CONF.set("editor", "wrap", True)

    font = CONF.get("appearance", "font/family")
    wrap = CONF.get("editor", "wrap")
    return font, wrap


def split_names(entries: Sequence[str]) -> set[str]:
    """Split repeated, comma-separated `--hide`/`--show` values into names."""
    return {
        name.strip()
        for entry in entries
        for name in entry.split(",")
        if name.strip()
    }


def resolve_hidden_paths(
    hide: Sequence[str] = (), show: Sequence[str] = ()
) -> list[str]:
    """Build the Project pane blocklist: the defaults, plus `hide`, minus `show`."""
    names = set(HIDDEN_PATHS) | split_names(hide)
    return sorted(names - split_names(show))


def write_launcher(conf_dir: Path, argv: Sequence[str], hidden: Sequence[str]) -> Path:
    """Write the launcher that patches the Project pane filter and starts Spyder."""
    launcher = conf_dir / "launch_spyder.py"
    launcher.write_text(
        LAUNCHER_TEMPLATE.format(argv=list(argv), hidden=list(hidden)),
        encoding="utf-8",
    )
    return launcher


def launch(
    spyder_args: Sequence[str] = (),
    *,
    no_launch: bool = False,
    keep_config: bool = False,
    workdir: str | Path | None = None,
    hide: Sequence[str] = (),
    show: Sequence[str] = (),
) -> int:
    """Configure Spyder 5.x, create `.spyproject` in the repository and open the IDE.

    From another repository::

        from setup_spyder import launch
        launch()
    """
    from setup_spyder import __version__

    workdir = Path(workdir).resolve() if workdir else Path.cwd().resolve()
    extra_args = [a for a in spyder_args if a != "--"]

    print_banner(__version__, workdir)
    print_env(workdir)

    try:
        import spyder
        import spyder_kernels
    except ImportError as exc:
        log_error(f"missing dependency ({exc}).")
        log("In the other repository, add this package:")
        log_kv("install", f"uv add git+{REPO_URL}")
        log("Or run it without installing into the project:")
        log_kv("oneshot", f"uvx --from git+{REPO_URL} setup-spyder")
        return 1

    log_ok(f"Spyder {spyder.__version__}  ·  spyder-kernels {spyder_kernels.__version__}")
    if not spyder.__version__.startswith("5."):
        log_warn(f"expected Spyder 5.x, got {spyder.__version__}")

    try:
        import pandas as pd
    except ImportError:
        log_warn("pandas is not installed in this environment")
    else:
        log_ok(f"pandas {pd.__version__}")

    font_family, fonts = resolve_editor_font()
    if fonts:
        log_ok(f"Font {font_family} found ({len(fonts)} file(s))")
        for path in fonts[:8]:
            log_kv("file", path)
        if len(fonts) > 8:
            log_kv("...", f"{len(fonts) - 8} more file(s)")

    spyproject = ensure_spyproject(workdir)

    conf_dir = Path(tempfile.mkdtemp(prefix="setup-spyder-conf-"))
    log(f"Isolated config at: {conf_dir}")
    log("(the user's ~/.spyder-py3 is left untouched)")

    try:
        font, wrap = apply_spyder_config(conf_dir, font_family=font_family)
        log_ok("Config written. Checking the values:")
        log_kv("appearance.font/family", font)
        log_kv("editor.wrap", wrap)

        ini_path = conf_dir / "config" / "spyder.ini"
        if ini_path.is_file():
            log(f"Config file: {ini_path}")
            log_kv("size", f"{ini_path.stat().st_size} bytes")
        else:
            log_warn(f"expected {ini_path}, but the file does not exist yet")

        if no_launch:
            log_ok("no_launch=True: setup finished without opening Spyder.")
            log(f"The Spyder project stays at {spyproject}")
            return 0

        spyder_argv = [
            shutil.which("spyder") or "spyder",
            "--conf-dir",
            str(conf_dir),
            "--new-instance",
            "-w",
            str(workdir),
            "-p",
            str(workdir),
            *extra_args,
        ]
        hidden = resolve_hidden_paths(hide, show)
        launcher = write_launcher(conf_dir, spyder_argv, hidden)
        log_ok(f"Hiding {len(hidden)} name(s) from the Project pane:")
        log_kv("hidden", ", ".join(hidden))

        cmd = [sys.executable, str(launcher)]
        log_ok("Opening Spyder now...")
        log_kv("command", " ".join(spyder_argv))
        log_kv("launcher", launcher)
        log("Close the Spyder window to finish (and delete the isolated config).")
        completed = subprocess.run(cmd, check=False)
        if completed.returncode == 0:
            log_ok(f"Spyder exited with code {completed.returncode}")
        else:
            log_warn(f"Spyder exited with code {completed.returncode}")
        return completed.returncode
    finally:
        if keep_config:
            log_warn(f"keep_config=True: keeping {conf_dir}")
        else:
            log(f"Removing isolated config: {conf_dir}")
            remove_tree(conf_dir)
            log_ok("Cleanup done.")


def parse_args(argv: Sequence[str] | None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        prog="setup-spyder",
        description=(
            "Install/use Spyder 5.x in an isolated environment, configure "
            f"{FONT_FAMILY} + wrap lines and open the IDE. "
            "Every step is printed to the terminal."
        ),
    )
    parser.add_argument(
        "--no-launch",
        action="store_true",
        help="Only configure; do not open the Spyder window.",
    )
    parser.add_argument(
        "--keep-config",
        action="store_true",
        help="Do not delete the isolated config directory on exit.",
    )
    parser.add_argument(
        "-w",
        "--workdir",
        default=None,
        help="Spyder working directory (default: current directory).",
    )
    parser.add_argument(
        "--hide",
        action="append",
        default=[],
        metavar="NAME[,NAME...]",
        help=(
            "Extra file/folder names to hide from the Project pane, on top of "
            f"the {len(HIDDEN_PATHS)} hidden by default. Repeatable."
        ),
    )
    parser.add_argument(
        "--show",
        action="append",
        default=[],
        metavar="NAME[,NAME...]",
        help="Names to keep visible, undoing a default (e.g. --show .github).",
    )
    parser.add_argument(
        "spyder_args",
        nargs=argparse.REMAINDER,
        help="Extra arguments forwarded to Spyder (after --).",
    )
    return parser.parse_args(argv)


def main(argv: Sequence[str] | None = None) -> int:
    args = parse_args(argv)
    return launch(
        args.spyder_args,
        no_launch=args.no_launch,
        keep_config=args.keep_config,
        workdir=args.workdir,
        hide=args.hide,
        show=args.show,
    )


if __name__ == "__main__":
    raise SystemExit(main())
