"""Integration routine: install the package from GitHub and open Spyder.

Creates the throwaway project in ``tests/fixture_integration/``, adds
``setup-spyder`` from GitHub and runs ``uv run setup-spyder`` inside it — the
same flow someone else would follow in another repository. At the end it prints
the summary and deletes everything it generated.

Usage::

    uv run setup-spyder-integration               # install from GitHub and open Spyder
    uv run setup-spyder-integration --no-launch   # only install and check the import
    uv run setup-spyder-integration --local       # use the working tree instead of GitHub
    uv run setup-spyder-integration --ref develop # install from another branch/tag
    uv run setup-spyder-integration --keep        # do not delete the test project at the end
"""

from __future__ import annotations

import argparse
import os
import shutil
import subprocess
from collections.abc import Sequence
from pathlib import Path
from typing import NamedTuple

from rich import box
from rich.console import Group
from rich.panel import Panel
from rich.table import Table
from rich.text import Text

from setup_spyder.cli import (
    REPO_URL,
    WINDOWS,
    console,
    force_writable,
    log,
    log_error,
    log_kv,
    log_ok,
    log_warn,
    remove_tree,
)

FIXTURE_RELPATH = Path("tests") / "fixture_integration"
FIXTURE_NAME = "setup-spyder-integration-fixture"

#: How to install ``uv`` when it is missing — PowerShell on Windows, shell elsewhere.
UV_INSTALL_WINDOWS = (
    'powershell -ExecutionPolicy ByPass -c "irm https://astral.sh/uv/install.ps1 | iex"'
)
UV_INSTALL_POSIX = "curl -LsSf https://astral.sh/uv/install.sh | sh"

#: Generated by the routine; wiped by ``--fresh`` and kept out of git.
GENERATED = (".venv", ".spyproject", "pyproject.toml", "uv.lock", "main.py")

#: Variables from the outer ``uv run`` that must not leak into the test project.
INHERITED_ENV_TO_DROP = (
    "VIRTUAL_ENV",
    "UV_PROJECT_ENVIRONMENT",
    "PYTHONPATH",
    "PYTHONHOME",
    "SPYDER_CONFDIR",
)

#: Kept in sync with ``requires-python`` in the repository's pyproject.toml.
FIXTURE_REQUIRES_PYTHON = ">=3.9"

FIXTURE_PYPROJECT = f"""\
# Generated by `uv run setup-spyder-integration` — do not edit by hand.
[project]
name = "{FIXTURE_NAME}"
version = "0.0.0"
description = "Throwaway project that consumes setup-spyder as a dependency."
requires-python = "{FIXTURE_REQUIRES_PYTHON}"
dependencies = []

[tool.uv]
package = false
"""

FIXTURE_MAIN = '''\
"""Example script opened by Spyder during the integration routine."""

# %% imports
import pandas as pd

from setup_spyder import __version__

# %% data
sales = pd.DataFrame(
    {
        "product": ["coffee", "tea", "coffee", "mate"],
        "region": ["south", "south", "north", "north"],
        "amount": [12.5, 8.0, 15.0, 6.5],
    }
)

# %% exploration
print(f"setup-spyder {__version__} · pandas {pd.__version__}")
print(sales.groupby("region")["amount"].sum())
'''


def find_repo_root(start: Path | None = None) -> Path:
    """Find the repository root by walking up from the cwd (or this file)."""
    seeds = [(start or Path.cwd()).resolve(), Path(__file__).resolve()]
    for seed in seeds:
        for directory in (seed, *seed.parents):
            if (directory / FIXTURE_RELPATH).is_dir():
                return directory
            if (directory / "src" / "setup_spyder" / "cli.py").is_file():
                return directory
    raise FileNotFoundError(
        "setup-spyder repository root not found; run this from inside the repo."
    )

def clean_fixture(fixture: Path) -> list[str]:
    """Delete what the routine generates, preserving what is versioned."""
    removed: list[str] = []
    for name in GENERATED:
        target = fixture / name
        if target.is_dir():
            remove_tree(target)
            removed.append(name)
        elif target.exists():
            force_writable(target)
            target.unlink()
            removed.append(name)
    return removed


def scaffold_fixture(fixture: Path) -> None:
    """Ensure the throwaway project's `pyproject.toml` and example script."""
    fixture.mkdir(parents=True, exist_ok=True)

    pyproject = fixture / "pyproject.toml"
    if pyproject.is_file():
        log_ok(f"pyproject.toml already exists: {pyproject}")
    else:
        pyproject.write_text(FIXTURE_PYPROJECT)
        log_ok(f"pyproject.toml created: {pyproject}")

    main_py = fixture / "main.py"
    if main_py.is_file():
        log_ok(f"main.py already exists: {main_py}")
    else:
        main_py.write_text(FIXTURE_MAIN)
        log_ok(f"main.py created: {main_py}")


def dependency_spec(root: Path, *, ref: str | None, local: bool) -> str:
    """Build the ``uv add`` target: local path or GitHub URL."""
    if local:
        return str(root)
    if ref:
        return f"git+{REPO_URL}@{ref}"
    return f"git+{REPO_URL}"


def child_env() -> dict[str, str]:
    """Clean environment: the outer ``uv run`` must not point at the wrong venv."""
    env = dict(os.environ)
    for key in INHERITED_ENV_TO_DROP:
        env.pop(key, None)
    return env


def run_step(
    cmd: Sequence[str], *, cwd: Path, title: str, capture: bool = False
) -> subprocess.CompletedProcess[str]:
    log(title)
    log_kv("command", " ".join(cmd))
    log_kv("cwd", cwd)
    completed = subprocess.run(
        list(cmd),
        cwd=cwd,
        env=child_env(),
        check=False,
        text=True,
        capture_output=capture,
    )
    if completed.returncode == 0:
        log_ok(f"{title} — ok")
    else:
        log_error(f"{title} — failed (code {completed.returncode})")
        if capture and completed.stderr:
            log(completed.stderr.strip())
    return completed


def short(value: object, root: Path) -> str:
    """Shrink paths and URLs so they fit on a single summary line."""
    text = str(value)
    if text.startswith("git+"):
        return text.removeprefix("git+").removeprefix("https://").removeprefix("github.com/")
    try:
        return str(Path(text).relative_to(root))
    except ValueError:
        return text


class Step(NamedTuple):
    """One stage of the routine, as it appears in the final summary."""

    title: str
    ok: bool
    detail: str


def print_summary(steps: Sequence[Step], *, code: int, location: str) -> None:
    """Final summary: one line per step, green if it passed, red if it did not."""
    table = Table(box=box.SIMPLE, show_header=False, padding=(0, 2), expand=False)
    table.add_column(justify="center", width=1)
    table.add_column(style="bold white")
    table.add_column(style="dim", overflow="fold")
    for step in steps:
        glyph = Text("✓", style="bold green") if step.ok else Text("✗", style="bold red")
        table.add_row(glyph, step.title, step.detail)

    ok = code == 0
    verdict = Text()
    verdict.append("Integration routine ", style="white")
    verdict.append("finished successfully" if ok else f"failed (code {code})",
                   style="bold green" if ok else "bold red")
    verdict.append("\n")
    verdict.append(location, style="dim")

    console.print()
    console.print(
        Panel(
            Group(verdict, Text(), table),
            title="[bold green]◆ integration ok[/]" if ok else "[bold red]◆ integration failed[/]",
            subtitle="[dim]throwaway test project · does not touch the main environment[/]",
            border_style="green" if ok else "red",
            box=box.ROUNDED,
            padding=(1, 2),
        )
    )
    console.print()


def cleanup_fixture(fixture: Path, *, keep: bool, failed: bool) -> None:
    """Delete what the routine generated — the test project is throwaway."""
    if keep:
        log_warn(f"--keep: keeping the test project at {fixture}")
        return

    log(f"Cleaning up the test project: {fixture}")
    removed = clean_fixture(fixture)
    for name in removed:
        log_kv("removed", name)
    if removed:
        log_ok("Fixture cleaned — nothing was left installed outside of it.")
    else:
        log_ok("Nothing to clean; the fixture was already empty.")
    if failed:
        log("Run with --keep to inspect the test project after a failure.")


def _run_steps(
    uv: str,
    root: Path,
    fixture: Path,
    spec: str,
    *,
    no_launch: bool,
    spyder_args: Sequence[str],
    steps: list[Step],
) -> int:
    scaffold_fixture(fixture)
    steps.append(Step("Test project created", True, short(fixture, root)))

    add = run_step(
        [uv, "add", "--refresh-package", "setup-spyder", spec],
        cwd=fixture,
        title="Installing setup-spyder",
    )
    steps.append(Step("setup-spyder installed", add.returncode == 0, short(spec, root)))
    if add.returncode:
        return 1

    check = run_step(
        [uv, "run", "python", "-c", "import setup_spyder; print(setup_spyder.__version__)"],
        cwd=fixture,
        title="Checking the setup_spyder import",
        capture=True,
    )
    version = check.stdout.strip()
    steps.append(
        Step(
            "import setup_spyder",
            check.returncode == 0,
            f"version {version}" if check.returncode == 0 else "import failed",
        )
    )
    if check.returncode:
        return 1
    log_kv("setup_spyder.__version__", version)

    launch_cmd = [uv, "run", "setup-spyder"]
    if no_launch:
        launch_cmd.append("--no-launch")
    extra = [arg for arg in spyder_args if arg != "--"]
    if extra:
        launch_cmd += ["--", *extra]

    completed = run_step(
        launch_cmd, cwd=fixture, title="Running Spyder in the test project"
    )
    steps.append(
        Step(
            "Spyder configured" if no_launch else "Spyder opened and closed",
            completed.returncode == 0,
            "uv " + " ".join(launch_cmd[1:]),
        )
    )
    return completed.returncode


def run_integration(
    *,
    ref: str | None = None,
    local: bool = False,
    fresh: bool = False,
    no_launch: bool = False,
    keep: bool = False,
    spyder_args: Sequence[str] = (),
) -> int:
    """Install the package into a fresh project, open Spyder and clean up at the end."""
    uv = shutil.which("uv")
    if uv is None:
        log_error("'uv' is not on PATH — install it:")
        log_kv("install uv", UV_INSTALL_WINDOWS if WINDOWS else UV_INSTALL_POSIX)
        return 1

    try:
        root = find_repo_root()
    except FileNotFoundError as exc:
        log_error(str(exc))
        return 1

    fixture = root / FIXTURE_RELPATH
    spec = dependency_spec(root, ref=ref, local=local)

    log_ok("setup-spyder integration routine")
    log_kv("repository", root)
    log_kv("test project", fixture)
    log_kv("dependency", spec)

    if fresh:
        removed = clean_fixture(fixture)
        log_ok(f"--fresh: removed {', '.join(removed)}" if removed else "--fresh: nothing to remove")

    steps = [
        Step("Isolated environment", True, "no inheritance from the outer uv run")
    ]
    code = 1
    try:
        code = _run_steps(
            uv, root, fixture, spec, no_launch=no_launch, spyder_args=spyder_args, steps=steps
        )
        return code
    finally:
        print_summary(steps, code=code, location=short(fixture, root))
        cleanup_fixture(fixture, keep=keep, failed=code != 0)


def parse_args(argv: Sequence[str] | None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        prog="setup-spyder-integration",
        description=(
            "Create the throwaway project in tests/fixture_integration, install "
            "setup-spyder from GitHub and open Spyder from there."
        ),
    )
    parser.add_argument(
        "--ref",
        default=None,
        help="GitHub branch, tag or commit (default: the repo's default branch).",
    )
    parser.add_argument(
        "--local",
        action="store_true",
        help="Install the local working tree instead of downloading from GitHub.",
    )
    parser.add_argument(
        "--fresh",
        action="store_true",
        help="Delete the test project before recreating it.",
    )
    parser.add_argument(
        "--no-launch",
        action="store_true",
        help="Only install and configure; do not open the Spyder window.",
    )
    parser.add_argument(
        "--keep",
        action="store_true",
        help="Do not delete the test project at the end (useful for inspection).",
    )
    parser.add_argument(
        "spyder_args",
        nargs=argparse.REMAINDER,
        help="Extra arguments forwarded to setup-spyder (after --).",
    )
    return parser.parse_args(argv)


def main(argv: Sequence[str] | None = None) -> int:
    args = parse_args(argv)
    if args.local and args.ref:
        log_warn("--ref is ignored together with --local")
    return run_integration(
        ref=args.ref,
        local=args.local,
        fresh=args.fresh,
        no_launch=args.no_launch,
        keep=args.keep,
        spyder_args=args.spyder_args,
    )


if __name__ == "__main__":
    raise SystemExit(main())
