"""Project pane filter applied inside the Spyder process, before the boot.

Spyder starts the IDE in-process, so the filter has to be patched before
``spyder.app.start`` builds the window. It reaches into Spyder internals, so it
is best-effort: on a Spyder that moved them, the IDE still opens, just with the
clutter visible. Nothing else is patched.
"""

from __future__ import annotations

import sys
from collections.abc import Sequence


def apply_project_pane_filter(hidden: Sequence[str]) -> bool:
    """Hide `hidden` (basenames) in the Project pane; True when the patch took."""
    names = set(hidden)
    if not names:
        return True
    try:
        from spyder.plugins.projects.widgets.projectexplorer import ProxyModel

        ProxyModel.PATHS_TO_HIDE = sorted(
            set(getattr(ProxyModel, "PATHS_TO_HIDE", [])) | names
        )
        # PATHS_TO_SHOW wins over PATHS_TO_HIDE, so drop whatever we are hiding.
        ProxyModel.PATHS_TO_SHOW = [
            path
            for path in getattr(ProxyModel, "PATHS_TO_SHOW", [])
            if path not in names
        ]
    except Exception as exc:
        print(
            "setup-spyder: could not hide files from the Project pane on this "
            f"Spyder version ({exc}); opening it anyway.",
            file=sys.stderr,
        )
        return False
    return True


#: Standalone script equivalent to ``python -m setup_spyder.bootstrap``: set
#: argv, filter the Project pane, start Spyder. Kept for callers that want a
#: file on disk; the launcher itself runs the bootstrap module directly.
LAUNCHER_TEMPLATE = '''\
"""Generated by setup-spyder — do not edit by hand.

Hides development clutter from Spyder's Project pane, then starts the IDE.
"""

import sys

# `spyder.app.start` parses the command line at import time, so argv comes first.
sys.argv = {argv!r}

HIDDEN = {hidden!r}

try:
    from spyder.plugins.projects.widgets.projectexplorer import ProxyModel

    ProxyModel.PATHS_TO_HIDE = sorted(
        set(getattr(ProxyModel, "PATHS_TO_HIDE", [])) | set(HIDDEN)
    )
    # PATHS_TO_SHOW wins over PATHS_TO_HIDE, so drop whatever we are hiding.
    ProxyModel.PATHS_TO_SHOW = [
        path
        for path in getattr(ProxyModel, "PATHS_TO_SHOW", [])
        if path not in HIDDEN
    ]
except Exception as exc:  # pragma: no cover - depends on the Spyder version
    print(
        "setup-spyder: could not hide files from the Project pane on this "
        f"Spyder version ({{exc}}); opening it anyway.",
        file=sys.stderr,
    )

from spyder.app.start import main

sys.exit(main())
'''


def render_launcher(argv: Sequence[str], hidden: Sequence[str]) -> str:
    """Render the standalone launcher script for `argv` and the `hidden` names."""
    return LAUNCHER_TEMPLATE.format(argv=list(argv), hidden=list(hidden))
